---
deployment:
  tasks:
    # Define the deploy path
    - export DEPLOYPATH=/home/abburuhari1/public_html/room-booking

    # Create the deploy path if it doesn't exist
    - /bin/mkdir -p $DEPLOYPATH

    # Copy all files including hidden ones recursively
    - /bin/cp -r . $DEPLOYPATH

    # Move into the project directory
    - cd $DEPLOYPATH

    # Ensure correct permissions
    - find storage -type d -exec chmod 775 {} \;
    - find bootstrap/cache -type d -exec chmod 775 {} \;

    # If composer is available on the server, install dependencies
    - if command -v composer >/dev/null 2>&1; then composer install --no-dev --prefer-dist --optimize-autoloader; fi

    # Set correct file ownership if needed (skip if you don’t have permission)
    # - chown -R youruser:yourgroup $DEPLOYPATH

    # Laravel app specific tasks
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan config:cache
    - php artisan migrate --force
